name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
        working-directory: BlockDAG-Automation/src/test/resources

      - name: Start Application
        run: mvn clean start  # Assuming 'start' is a valid goal/command in your setup
        working-directory: qa-automations-scripts-main/BlockDAG-Automation

      - name: Run Tests
        run: mvn test
        working-directory: BlockDAG-Automation/src/test/resources

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: BlockDAG-Automation/test-output/emailable-report.html
