name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Tests
        run: mvn test -DsuiteXmlFile=src/test/resources/testng.xml
        working-directory: BlockDAG-Automation

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: BlockDAG-Automation/target/surefire-reports

      - name: Upload Emailable Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: emailable-report
          path: BlockDAG-Automation/test-output/emailable-report.html

      # ✅ Configure AWS CLI with OIDC
      - name: Configure AWS CLI with OIDC
        run: |
          aws sts get-caller-identity
        env:
          AWS_REGION: us-east-1  # Update this with your region

      # ✅ Upload reports to S3
      - name: Upload Test Reports to S3
        run: |
          aws s3 cp BlockDAG-Automation/target/surefire-reports s3://stage-test-report-blockdag/surefire-reports/ --recursive
          aws s3 cp BlockDAG-Automation/test-output/emailable-report.html s3://stage-test-report-blockdag/emailable-report.html
