name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125780543:role/stage-oidc-blockdag
          aws-region: eu-central-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Determine Environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=mainnet" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=stage" >> $GITHUB_ENV
          fi

      - name: Run Tests
        run: |
          if [[ "$ENVIRONMENT" == "mainnet" ]]; then
            mvn clean test -D=https://bdagscan.com
          else
            mvn test -DsuiteXmlFile=src/test/resources/testng.xml
          fi
        working-directory: BlockDAG-Automation

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: BlockDAG-Automation/target/surefire-reports

      - name: Upload ExtentReport
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: BlockDAG-Automation/test-output/ExtentReport.html

      # ✅ Upload reports to S3
      - name: Upload Test Reports to S3
        if: always()
        run: |
          # Get current date and time
          CURRENT_DATE=$(date +'%Y/%m/%d')
          CURRENT_TIME=$(date +'%H-%M-%S')
          
          # Determine the S3 path based on the environment
          if [[ "$ENVIRONMENT" == "mainnet" ]]; then
            S3_PATH="mainnet/${CURRENT_DATE}/${CURRENT_TIME}/"
          else
            S3_PATH="stage/${CURRENT_DATE}/${CURRENT_TIME}/"
          fi
          
          # Upload Surefire Reports
          aws s3 cp BlockDAG-Automation/target/surefire-reports s3://stage-test-report-blockag/${S3_PATH}surefire-reports/ --recursive
          
          # Upload ExtentReport
          aws s3 cp BlockDAG-Automation/test-output/ExtentReport.html s3://stage-test-report-blockag/${S3_PATH}ExtentReport.html
