name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'  # Using built-in caching for Maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install
        working-directory: BlockDAG-Automation

      - name: Run Tests
        run: mvn test -DsuiteXmlFile=src/test/resources/testng.xml
        working-directory: BlockDAG-Automation

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: BlockDAG-Automation/target/surefire-reports

      - name: Upload Emailable Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: emailable-report
          path: BlockDAG-Automation/test-output/emailable-report.html
