name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
        working-directory: BlockDAG-Automation  # Build from the directory containing pom.xml

      - name: Start Application
        run: mvn clean start  # Assuming 'start' is a valid goal/command in your setup
        working-directory: BlockDAG-Automation  # Start the application from the root directory

      - name: Run Tests
        run: mvn clean test -DsuiteXmlFile=src/test/resources/testng.xml  # Specify the location of your testng.xml
        working-directory: BlockDAG-Automation  # Run tests from the root directory

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: BlockDAG-Automation/test-output/emailable-report.html
