name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125780543:role/stage-oidc-blockdag
          aws-region: eu-central-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Run Tests for Mainnet
        id: mainnet
        run: |
          mvn clean test -D=https://bdagscan.com
        working-directory: BlockDAG-Automation

      - name: Upload Mainnet Reports to S3
        if: always()
        run: |
          # Get current date and time
          CURRENT_DATE=$(date +'%Y/%m/%d')
          CURRENT_TIME=$(date +'%H-%M-%S')
          S3_PATH="mainnet/${CURRENT_DATE}/${CURRENT_TIME}/"
          
          # Upload Surefire Reports
          aws s3 cp BlockDAG-Automation/target/surefire-reports s3://stage-test-report-blockag/${S3_PATH}surefire-reports/ --recursive
          
          # Upload ExtentReport
          aws s3 cp BlockDAG-Automation/test-output/ExtentReport.html s3://stage-test-report-blockag/${S3_PATH}ExtentReport.html

      - name: Run Tests for Stage
        id: stage
        run: |
          mvn test -DsuiteXmlFile=src/test/resources/testng.xml
        working-directory: BlockDAG-Automation

      - name: Upload Stage Reports to S3
        if: always()
        run: |
          # Get current date and time
          CURRENT_DATE=$(date +'%Y/%m/%d')
          CURRENT_TIME=$(date +'%H-%M-%S')
          S3_PATH="stage/${CURRENT_DATE}/${CURRENT_TIME}/"
          
          # Upload Surefire Reports
          aws s3 cp BlockDAG-Automation/target/surefire-reports s3://stage-test-report-blockag/${S3_PATH}surefire-reports/ --recursive
          
          # Upload ExtentReport
          aws s3 cp BlockDAG-Automation/test-output/ExtentReport.html s3://stage-test-report-blockag/${S3_PATH}ExtentReport.html
